#!/bin/bash

set -e

case "$1" in
  remove)
    for i in /var/log/datum-gateway; do
      if dpkg-statoverride --list $i >/dev/null 2>&1; then
          dpkg-statoverride --remove $i
      fi
    done
    ;;
  purge)
    
    if [ -d /etc/datum-gateway ]; then
      rm -rf /etc/datum-gateway
    fi

    for i in /var/log/datum-gateway; do
      if dpkg-statoverride --list $i >/dev/null 2>&1; then
          dpkg-statoverride --remove $i
      fi
    done
    ;;
    
  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
esac


#DEBHELPER#

exit 0